#!/usr/bin/env bash
if [[ $1 = "install" ]]
then
  if [[ $2 != "" ]]
  then
    echo -e "\033[1;34m==>\033[22;0m Checking internet connectivity"
    wget -q --tries=10 --timeout=20 --spider http://github.com
    if [[ $? -eq 0 ]]; then
            echo -e "\033[1;34m==>\033[22;0m Retrieving latest package information"
            curl -# https://raw.githubusercontent.com/supermarin/alcatraz-packages/master/packages.json > /Library/Caches/Alcatraz/packages.json
            URL=$(jq -r ".packages.plugins | .[] | select(.name==\"$2\") | .url" < /Library/Caches/Alcatraz/packages.json)
    else
            echo "\033[1;31m==>\033[22;0m Unable to retrieve latest package list."
            exit
    fi
    if [[ $URL != "" ]]
    then
      echo -e "\033[1;34m==>\033[22;0m Downloading source repository for $2"
      [ -d "/Library/Caches/Alcatraz/Sources/$2" ] || git clone $URL.git /Library/Caches/Alcatraz/Sources/$2
      echo -e "\033[1;34m==>\033[22;0m Building $2"
      cd "/Library/Caches/Alcatraz/Sources/$2" ; git pull >/dev/null 2>&1 ; xcodebuild >/dev/null 2>&1
      echo -e "\033[1;32mBuilt and installed plugin: $2\033[22;0m"
      exit
    fi
    URL=$(jq -r ".packages.color_schemes | .[] | select(.name==\"$2\") | .url" < /Library/Caches/Alcatraz/packages.json)
    if [[ $URL != "" ]]
    then
      echo -e "\033[1;34m==>\033[22;0m Downloading color scheme file for $2"
      [ -d ~/Library/Developer/Xcode/UserData/FontAndColorThemes ] || mkdir ~/Library/Developer/Xcode/UserData/FontAndColorThemes
      cd ~/Library/Developer/Xcode/UserData/FontAndColorThemes/; curl -L#so "$2.dvtcolortheme" $URL
      echo -e "\033[1;32mInstalled color scheme: $2\033[22;0m"
      exit
    fi
  fi
fi

if [[ $1 = "uninstall" ]]
then
  if [ -d "/Users/$(whoami)/Library/Application Support/Developer/Shared/Xcode/Plug-ins/$2.xcplugin" ]
  then
    (rm -r "/Users/$(whoami)/Library/Application Support/Developer/Shared/Xcode/Plug-ins/$2.xcplugin" >/dev/null 2>&1 && echo -e "\033[1;32m$2 plugin has been removed from your system.\033[22;0m") || echo -e "\033[1;31m$2 is not installed\033[22;0m"
    exit
  fi
  if [ -e "/Users/$(whoami)/Library/Developer/Xcode/UserData/FontAndColorThemes/$2.dvtcolortheme" ]
  then
    ( rm "/Users/$(whoami)/Library/Developer/Xcode/UserData/FontAndColorThemes/$2.dvtcolortheme" >/dev/null 2>&1 && echo -e "\033[1;32m$2 color scheme has been removed from your system.\033[22;0m" ) || echo -e "\033[1;31m$2 is not installed\033[22;0m"
    exit
  fi
fi

if [[ $1 = "clean" ]]
then
  if [ -d "/Library/Caches/Alcatraz" ]
  then
    echo -e "\033[1;34m==>\033[22;0m Removing the cache directory"
    rm -rf /Library/Caches/Alcatraz
    exit 0
  else
    echo -e "\033[1;31m==>\033[22;0m Cache directory is absent"
    exit 1
  fi
fi

echo -e "\033[1;34malc - the CLI tool for Alcatraz\033[22;0m"
echo -e "by Caleb Xu\n"
echo "Based on the package repository managed by Marin Usalj"\
